name: Build on tag
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      go-version: "1.25.8"
    steps:
      - uses: actions/checkout@v5
      - name: setup go ${{ env.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
      - name: build program
        run: |
          go get .
          go build -ldflags "-s -w" -o fs .
      - name: create release with artifact
        uses: softprops/action-gh-release@v2
        with:
          files: fs
